Update nextjs.yml

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -93,3 +93,18 @@ jobs:
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v2
+
+  if [ -f "/home/runner/work/first/first/yarn.lock" ]; then
+    echo "manager=yarn" >> $GITHUB_OUTPUT
+    echo "command=install" >> $GITHUB_OUTPUT
+    echo "runner=yarn" >> $GITHUB_OUTPUT
+    exit 0
+  elif [ -f "/home/runner/work/first/first/package.json" ]; then
+    echo "manager=npm" >> $GITHUB_OUTPUT
+    echo "command=ci" >> $GITHUB_OUTPUT
+    echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+    exit 0
+  else
+    echo "Unable to determine package manager"
+    exit 1
+  fi
